# Generated by Django 4.1.7 on 2023-03-10 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shtat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stf_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(blank=True, default='XXXX', max_length=20)),
                ('last_name', models.CharField(blank=True, default='XXXX', max_length=20)),
                ('pic', django_resized.forms.ResizedImageField(crop=None, default='default/default.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[200, 200], upload_to=login.models.get_image_path)),
                ('pic_thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[40, 40], upload_to=login.models.get_image_path)),
                ('pic_140x', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[140, 140], upload_to=login.models.get_image_path)),
                ('shtat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.shtat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
