# Generated by Django 4.1.7 on 2023-03-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firs_name',
            field=models.CharField(blank=True, default='XXXX', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, default='XXXX', max_length=20),
        ),
    ]
