# Generated by Django 4.1.7 on 2023-03-10 06:17

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pic_140x',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pic_thumbnail',
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='img/default.jpg', upload_to=login.models.get_image_path),
        ),
    ]
