# Generated by Django 4.1.7 on 2023-03-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile_firs_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic_140x',
            field=models.ImageField(blank=True, default='default/thumbnail.jpg', null=True, upload_to='img'),
        ),
    ]
