# Generated by Django 4.1.7 on 2023-03-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_profile_pic_140x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='default/default.jpg', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic_140x',
            field=models.ImageField(default='default/thumbnail.jpg', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic_thumbnail',
            field=models.ImageField(default='default/thumbnail.jpg', upload_to='img'),
        ),
    ]
