# Generated by Django 4.1.7 on 2023-03-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_profile_pic_alter_profile_pic_140x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic_140x',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
