# Generated by Django 4.1.7 on 2023-03-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_profile_pic_140x_alter_profile_pic_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='img'),
        ),
    ]
